name: Convo Automation Task - Selenium CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 AM UTC

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Chrome and ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt install -f
          google-chrome --version
          
          # Fetch the latest ChromeDriver version matching the installed Chrome
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f1)
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
          
          wget -N https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip -o chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
          chromedriver --version

      - name: Display System Information
        run: |
          echo "System Information:"
          uname -a
          java -version
          mvn -version
          google-chrome --version
          chromedriver --version

      - name: Install Maven Dependencies
        run: mvn clean install -DskipTests=true

      - name: Run Selenium TestNG Tests
        run: mvn clean test -Dsurefire.suiteXmlFiles=./testng.xml -Dsurefire.rerunFailingTestsCount=2 --fail-at-end

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports
